version: "3.0"
services:
  escola-service:
    build:
      context: .
    ports:
      - "7085:7085"
    container_name: UpsService
    volumes:
      - ./app:/app/app
      - ./dominio:/app/dominio
      - ./repositorio:/app/repositorio
      - ./service:/app/service
      - ./test:/app/test
